# Generated by Django 4.2.7 on 2023-11-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoIoT', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadosdosensor',
            old_name='valor',
            new_name='acceleration_x',
        ),
        migrations.AddField(
            model_name='dadosdosensor',
            name='acceleration_y',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
